### ISSUE TITLE
what is stored in the field temp_p?

### ISSUE THREAD

**Issue by markcroft1975** [raspberrypilearning/astro-pi-flight-data-analysis#2]
hi

not clear in the documentation/worksheets 

https://github.com/raspberrypilearning/astro-pi-flight-data-analysis/blob/master/worksheet.md

temp_h	The temperature in degrees Celsius.	Sense HAT Humidity sensor.
temp_p	The temperature in degrees Celsius.	Sense HAT Pressure sensor.

what does HAT stand for?
does the pressure sensor also have a temperature?

thx
good work

**Comment by davidhoness** [comment]
The Sense HAT is the add on board used by the Astro Pi flight hardware. HAT stands for Hardware Attached on Top which is a standard for Raspberry Pi peripherals.

temp_h = temperature read by the humidity sensor
temp_p = temperature read by the pressure sensor

**Comment by markcroft1975** [comment]
i still think the worksheet is not clear enough to explain the difference temperature readings

**Comment by markcroft1975** [comment]
sorry my english is bad i have dyselixa
